2024-09-08 07:00:27,612 |           flt.mkdocs |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/mkdocs.py", line 201, in make
    raise RuntimeError(f'MkDocs cannot make {target}\nmkdocs logs:\n {mkdocs_output}')
RuntimeError: MkDocs cannot make site
mkdocs logs:
 INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /usr/src/app/echolore.mkdocs
[31mERROR    -  [0mConfiguration error: tags.md doesn't exist.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/mkdocs.py", line 232, in make
    raise RuntimeError(f'Build failed: {exception}')
RuntimeError: Build failed: MkDocs cannot make site
mkdocs logs:
 INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /usr/src/app/echolore.mkdocs
[31mERROR    -  [0mConfiguration error: tags.md doesn't exist.


2024-09-08 07:00:27,617 |                  flt | CRITICAL | No result returned by backend
